(() => {
'use strict';
const lesson=window.CLOVER_LESSON8, refs=window.CLOVER_LESSON8_REFERENCES, learning=window.CLOVER_LESSON8_LEARNING;
if(!lesson||!refs||!learning) throw new Error('Clover Lesson 8 data is missing.');
const $=id=>document.getElementById(id);
const el={stage:$('stage'),prev:$('prevBtn'),next:$('nextBtn'),menu:$('menuBtn'),map:$('mapBtn'),reset:$('resetBtn'),counter:$('counter'),bar:$('progressBar'),voiceMode:$('voiceMode'),rate:$('rate'),rateValue:$('rateValue'),menuOverlay:$('menuOverlay'),menuBody:$('menuBody'),menuClose:$('menuClose'),mapOverlay:$('mapOverlay'),mapBody:$('mapBody'),mapClose:$('mapClose'),toast:$('toast')};
const params=new URLSearchParams(location.search), schoolYear=params.get('year')||String(new Date().getFullYear()), className=params.get('class')||'default', resume=params.get('resume')==='1';
const progressKey=`clover.progress.${schoolYear}.${className}.${lesson.id}`, voiceKey=`${lesson.id}.voice`, rateKey=`${lesson.id}.rate`;
const names={problem:'問題',hint1:'Hint 1',hint2:'Hint 2',check:'Check',why:'Why?',wrong:'誤答分析',meaning:'Meaning',grammar:'文法整理',output:'Back Up'};
const stagesFor=i=>['problem',...(i.hints||[]).map((_,n)=>`hint${n+1}`),'check','why',...((i.wrong||[]).length?['wrong']:[]),'meaning',...((i.sourceRefs||[]).length?['grammar']:[]),...(i.output?.phrases?.length?['output']:[])];
const frames=[{kind:'cover'},{kind:'map'}]; lesson.items.forEach((i,itemIndex)=>stagesFor(i).forEach(stage=>frames.push({kind:'item',itemIndex,stage}))); frames.push({kind:'finalq'},{kind:'finala'});
let frameIndex=0, backupHiddenCount=0, backupJapaneseOnly=false, toastTimer=null;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const frame=()=>frames[frameIndex], item=()=>frame().kind==='item'?lesson.items[frame().itemIndex]:null;
function speechBlank(t){return String(t).replace(/\(\s*[A-Za-z]?\s*[　 ]*\)/g,' blank ').replace(/\(　+\)/g,' blank ').replace(/[①②③④⑤]/g,'');}
window.LessonAudio={speak(i,stage='problem'){if(!('speechSynthesis'in window)||!i)return;speechSynthesis.cancel();let text=(stage==='problem'||stage.startsWith('hint'))?(i.subQuestions?.length?i.subQuestions.join('. '):i.question):(i.completed||i.answer||i.question);if(stage==='problem'||stage.startsWith('hint'))text=speechBlank(text);const u=new SpeechSynthesisUtterance(text),vs=speechSynthesis.getVoices(),mode=el.voiceMode?.value||'auto';const v=mode==='en-GB'?vs.find(x=>/^en-GB/i.test(x.lang)):mode==='en-US'?vs.find(x=>/^en-US/i.test(x.lang)):vs.find(x=>/^en/i.test(x.lang));if(v)u.voice=v;u.lang=v?.lang||(mode==='en-GB'?'en-GB':'en-US');u.rate=Math.min(3,Math.max(.7,Number(el.rate?.value)||1));speechSynthesis.speak(u);}};
function toast(msg){clearTimeout(toastTimer);el.toast.textContent=msg;el.toast.hidden=false;toastTimer=setTimeout(()=>el.toast.hidden=true,1600);}
function save(){localStorage.setItem(progressKey,JSON.stringify({frameIndex,backupHiddenCount,backupJapaneseOnly,updatedAt:new Date().toISOString()}));}
function restore(){if(!resume)return;try{const p=JSON.parse(localStorage.getItem(progressKey)||'null');if(p&&Number.isInteger(p.frameIndex)&&p.frameIndex>=0&&p.frameIndex<frames.length){frameIndex=p.frameIndex;backupHiddenCount=Number(p.backupHiddenCount)||0;backupJapaneseOnly=!!p.backupJapaneseOnly;setTimeout(()=>toast(`${schoolYear} ${className} の続きから再開`),0);}}catch(_){}}
function toolbar(){const f=frame(),i=item();el.counter.textContent=f.kind==='cover'?'Clover Lesson 8':f.kind==='map'?'Grammar Map':f.kind==='finalq'||f.kind==='finala'?'Final Check':`${i.key} · ${names[f.stage]||f.stage}`;el.bar.style.width=`${(frameIndex/(frames.length-1)*100).toFixed(1)}%`;el.prev.disabled=frameIndex===0&&backupHiddenCount===0;}
const audio=()=>`<button class="audio-btn" type="button" data-audio="1" aria-label="英文を読み上げ">▶</button>`;
function qblock(i,reveal=false){let h=`<div class="question-card">${audio()}<p class="question">${esc(i.question)}</p>`;if(i.subQuestions?.length)h+=`<div class="sub-question-list">${i.subQuestions.map((s,n)=>`<div class="sub-question">${String.fromCharCode(97+n)}. ${esc(s)}</div>`).join('')}</div>`;if(i.choices?.length)h+=`<div class="choice-grid">${i.choices.map(c=>`<div class="choice ${reveal&&(i.answer.includes(c)||c.includes(i.answer.replace(/^[①②③④⑤]\s*/,'')))?'correct':''}">${esc(c)}</div>`).join('')}</div>`;return h+'</div>';}
const top=(i,s)=>`<div class="topline"><span class="qno">${esc(i.key)}</span><span class="section-pill">${esc(i.sectionName)}</span><span class="focus-pill">${esc(i.focus)}</span><span class="stage-pill">${esc(names[s]||s)}</span></div><h2 class="lesson-title">Clover Lesson 8</h2>`;
function mapHtml(full=true){return `<div class="map-head"><div><div class="eyebrow">WHOLE MAP</div><h2>高校英文法 Grammar Map</h2></div><p>色のついた領域が Lesson 8 で実際に使う範囲。<br>問題番号までつなげて「どこを見て解くか」を確認します。</p></div><div class="map-grid">${refs.grammarMap.map(n=>`<div class="map-node ${n.active?'active':''}"><div class="map-no">${esc(n.no)}</div><div class="map-name">${esc(n.name)}</div><div class="map-axis">${esc(n.axis)}</div>${n.active?`<div class="map-qs">${esc(n.questions.join(' / '))}</div>`:''}</div>`).join('')}</div>${full?`<div class="lesson-core">${learning.lessonCore.map(c=>`<div class="core-card"><b>${esc(c.title)}</b><p>${esc(c.body)}</p><div class="core-ex">${c.examples.map(esc).join('<br>')}</div></div>`).join('')}</div>`:''}`;}
function cover(){el.stage.className='stage cover-stage';el.stage.innerHTML=`<div class="stage-scroll"><div class="stage-inner"><div class="eyebrow">CLOVER · LESSON 8</div><h1>答えではなく<br>判断基準を持ち帰る。</h1><p class="cover-lead">37問を、問題 → Hint → Check → Why? → 誤答分析 → 文法整理 → 必要なOutput の順で進めます。問題・解答・訳を正確に保ちながら、Lesson 8で散在する文法を1枚の地図につなぎます。</p><div class="cover-badges"><span>37 questions</span><span>Wrong-answer analysis</span><span>Grammar Map</span><span>Phrase-by-phrase Back Up</span></div></div></div>`;}
function map(){el.stage.className='stage';el.stage.innerHTML=`<div class="stage-scroll"><div class="stage-inner">${mapHtml(true)}</div></div>`;}
function hint(i,s){const n=Number(s.replace('hint',''))-1;return `${top(i,s)}${qblock(i)}<section class="panel"><div class="panel-label label-hint">💡 Hint ${n+1}</div><div class="hint-box">${esc(i.hints[n])}</div></section>`;}
function check(i){return `${top(i,'check')}${qblock(i,true)}<section class="panel"><div class="panel-label label-check">✓ Check</div><div class="big-answer">${esc(i.answer)}</div>${i.corrected?`<div class="decision"><b>訂正：</b>${esc(i.corrected)}</div>`:''}<div class="completed">${esc(i.completed)}</div></section>`;}
function why(i){return `${top(i,'why')}${qblock(i,true)}<section class="panel"><div class="panel-label label-why">🔎 Why?</div><ul class="explain-list">${(i.why||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul><div class="decision"><b>次に同じタイプが出たら：</b> ${esc(i.decision||'')}</div></section>`;}
function wrong(i){return `${top(i,'wrong')}${qblock(i,true)}<section class="panel"><div class="panel-label label-wrong">✕ なぜそれを選びたくなる？ どこで切る？</div><div class="wrong-grid">${i.wrong.map(x=>`<div class="wrong-item">${esc(x)}</div>`).join('')}</div></section>`;}
function meaning(i){const t=i.translations?.length?`<ul class="explain-list">${i.translations.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:`<p class="translation">${esc(i.translation||'')}</p>`;return `${top(i,'meaning')}${qblock(i,true)}<section class="panel"><div class="panel-label label-meaning">🌿 Meaning / 日本語</div>${t}</section>`;}
function grammar(i){const cards=(i.sourceRefs||[]).map(k=>refs.cards[k]).filter(Boolean);return `${top(i,'grammar')}<section class="panel"><div class="panel-label label-grammar">🧭 この問題を全体地図へ戻す</div>${cards.map(c=>`<div class="grammar-card"><h3>${esc(c.title)}</h3><div><ul class="grammar-rules">${c.rules.map(r=>`<li>${esc(r)}</li>`).join('')}</ul><div class="grammar-check">判断手順：${esc(c.check)}</div></div></div>`).join('')}</section>`;}
function output(i){const ps=i.output.phrases,start=Math.max(0,ps.length-backupHiddenCount),line=ps.map((p,n)=>`<span class="phrase ${n>=start?'hidden-phrase':''}">${n>=start?'hidden':esc(p)}</span>`).join('');return `${top(i,'output')}<section class="panel"><div class="panel-label label-output">🎙 Back Up Technique</div><div class="backup-wrap ${backupJapaneseOnly?'backup-only-jp':''}"><div class="backup-jp">${esc(i.output.jp)}</div><div class="phrase-line">${line}</div><div class="backup-status"><span>${backupJapaneseOnly?'日本語だけから再生':`隠したフレーズ ${backupHiddenCount} / ${ps.length}`}</span><button class="mini-btn" type="button" data-backup-reset="1">最初に戻す</button></div></div></section><div class="decision"><b>操作：</b> → を1回押すたびに、文末側から <strong>1フレーズだけ</strong> 消えます。全文を一気には消しません。</div>`;}
function itemFrame(f){const i=lesson.items[f.itemIndex];let b=f.stage==='problem'?`${top(i,'problem')}${qblock(i)}<section class="panel"><div class="panel-label">👀 Think</div><div class="hint-box">まず自力で。必要なら → で Hint へ。</div></section>`:f.stage.startsWith('hint')?hint(i,f.stage):f.stage==='check'?check(i):f.stage==='why'?why(i):f.stage==='wrong'?wrong(i):f.stage==='meaning'?meaning(i):f.stage==='grammar'?grammar(i):output(i);el.stage.className='stage';el.stage.innerHTML=`<div class="stage-scroll"><div class="stage-inner">${b}</div></div>`;}
function final(show){el.stage.className='stage';el.stage.innerHTML=`<div class="stage-scroll"><div class="stage-inner"><div class="topline"><span class="qno">FINAL</span><span class="section-pill">One Last Try</span><span class="stage-pill">${show?'答え合わせ':'考える'}</span></div><h2 class="lesson-title">Lesson 8 Final Check</h2><section class="panel"><div class="panel-label ${show?'label-check':'label-hint'}">${show?'✓ 判断基準を再現':'? 6つを口頭で即答'}</div><div class="final-grid">${learning.finalCheck.map((c,n)=>`<div class="final-card"><div class="final-q">${n+1}. ${esc(c.q)}</div>${show?`<div class="final-a">${esc(c.a)}</div><div class="final-why">${esc(c.why)} <b>→ ${esc(c.refs.join(' / '))}</b></div>`:'<div class="final-a">？</div>'}</div>`).join('')}</div></section>${show?'<div class="decision"><b>Lesson 8 のゴール：</b> 正答を暗記するのではなく、次に同型が出たとき「どこを見るか」を言えること。</div>':''}</div></div>`;}
function render(){const f=frame();if(f.kind!=='item'||f.stage!=='output'){backupHiddenCount=0;backupJapaneseOnly=false;}if(f.kind==='cover')cover();else if(f.kind==='map')map();else if(f.kind==='item')itemFrame(f);else final(f.kind==='finala');toolbar();save();const s=el.stage.querySelector('.stage-scroll');if(s)s.scrollTop=0;window.dispatchEvent(new CustomEvent('clover:framechange',{detail:{frame:f,item:item(),schoolYear,className}}));}
function advance(){const f=frame();if(f.kind==='item'&&f.stage==='output'){const total=item().output.phrases.length;if(backupHiddenCount<total){backupHiddenCount++;render();return;}if(!backupJapaneseOnly){backupJapaneseOnly=true;render();return;}}if(frameIndex<frames.length-1){frameIndex++;backupHiddenCount=0;backupJapaneseOnly=false;render();}else toast('Lesson 8 完了');}
function back(){const f=frame();if(f.kind==='item'&&f.stage==='output'){if(backupJapaneseOnly){backupJapaneseOnly=false;render();return;}if(backupHiddenCount>0){backupHiddenCount--;render();return;}}if(frameIndex>0){frameIndex--;backupHiddenCount=0;backupJapaneseOnly=false;render();}}
function reset(){backupHiddenCount=0;backupJapaneseOnly=false;const f=frame();if(f.kind==='item'){const p=frames.findIndex(x=>x.kind==='item'&&x.itemIndex===f.itemIndex&&x.stage==='problem');if(p>=0)frameIndex=p;}render();}
function closeAll(){el.menuOverlay.hidden=true;el.mapOverlay.hidden=true;}
function jump(n){const p=frames.findIndex(f=>f.kind==='item'&&f.itemIndex===n&&f.stage==='problem');if(p>=0){frameIndex=p;backupHiddenCount=0;backupJapaneseOnly=false;closeAll();render();}}
el.menuBody.innerHTML=`<div class="jump-grid">${lesson.items.map((i,n)=>`<button class="jump-btn" type="button" data-jump="${n}"><b>${esc(i.key)} ${esc(i.sectionName)}</b><small>${esc(i.focus)}</small></button>`).join('')}</div>`; el.mapBody.innerHTML=mapHtml(false);
el.next.addEventListener('click',advance);el.prev.addEventListener('click',back);el.reset.addEventListener('click',reset);el.menu.addEventListener('click',()=>el.menuOverlay.hidden=false);el.map.addEventListener('click',()=>el.mapOverlay.hidden=false);el.menuClose.addEventListener('click',()=>el.menuOverlay.hidden=true);el.mapClose.addEventListener('click',()=>el.mapOverlay.hidden=true);[el.menuOverlay,el.mapOverlay].forEach(o=>o.addEventListener('click',e=>{if(e.target===o)o.hidden=true;}));el.menuBody.addEventListener('click',e=>{const b=e.target.closest('[data-jump]');if(b)jump(Number(b.dataset.jump));});
el.stage.addEventListener('click',e=>{const a=e.target.closest('[data-audio]');if(a){e.stopPropagation();if(item())LessonAudio.speak(item(),frame().stage||'problem');return;}const r=e.target.closest('[data-backup-reset]');if(r){e.stopPropagation();backupHiddenCount=0;backupJapaneseOnly=false;render();return;}if(e.target.closest('button,input,select,textarea,a'))return;advance();});
document.addEventListener('keydown',e=>{if(!el.menuOverlay.hidden||!el.mapOverlay.hidden){if(e.key==='Escape')closeAll();return;}if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight'||e.key===' '||e.key==='Enter'){e.preventDefault();advance();}else if(e.key==='ArrowLeft'){e.preventDefault();back();}else if(e.key.toLowerCase()==='m')el.mapOverlay.hidden=false;});
if(el.rate){const s=localStorage.getItem(rateKey);if(s)el.rate.value=s;el.rateValue.textContent=Number(el.rate.value).toFixed(1);el.rate.addEventListener('input',()=>{el.rateValue.textContent=Number(el.rate.value).toFixed(1);localStorage.setItem(rateKey,el.rate.value);});}if(el.voiceMode){const s=localStorage.getItem(voiceKey);if(s)el.voiceMode.value=s;el.voiceMode.addEventListener('change',()=>localStorage.setItem(voiceKey,el.voiceMode.value));}
window.CloverLesson8App={getCurrentItem:item,getCurrentFrame:frame,getContext:()=>({schoolYear,className,progressKey}),jumpToItem:jump,openMap:()=>el.mapOverlay.hidden=false,advance,back,getBackupState:()=>({hiddenCount:backupHiddenCount,japaneseOnly:backupJapaneseOnly}),_frames:frames};
restore();render();
})();
